"""Add Balance General accounting tables

Revision ID: 60744af94978
Revises: afefdd76db63
Create Date: 2025-12-09 01:08:51.221521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60744af94978'
down_revision = 'afefdd76db63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_payable',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_ap_amount_positive'),
    sa.CheckConstraint('amount_paid >= 0', name='chk_ap_paid_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_payable_school_id'), 'accounts_payable', ['school_id'], unique=False)
    op.create_table('balance_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET_CURRENT', 'ASSET_FIXED', 'ASSET_OTHER', 'LIABILITY_CURRENT', 'LIABILITY_LONG', 'LIABILITY_OTHER', 'EQUITY_CAPITAL', 'EQUITY_RETAINED', 'EQUITY_OTHER', name='account_type_enum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('original_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('accumulated_depreciation', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('useful_life_years', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('creditor', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("balance >= 0 OR account_type::text LIKE 'LIABILITY%' OR account_type::text LIKE 'EQUITY%'", name='chk_balance_account_sign'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_accounts_account_type'), 'balance_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_balance_accounts_school_id'), 'balance_accounts', ['school_id'], unique=False)
    op.create_table('balance_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['balance_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_entries_account_id'), 'balance_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_balance_entries_entry_date'), 'balance_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_balance_entries_school_id'), 'balance_entries', ['school_id'], unique=False)
    op.create_table('accounts_receivable',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_ar_amount_positive'),
    sa.CheckConstraint('amount_paid >= 0', name='chk_ar_paid_positive'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_receivable_client_id'), 'accounts_receivable', ['client_id'], unique=False)
    op.create_index(op.f('ix_accounts_receivable_school_id'), 'accounts_receivable', ['school_id'], unique=False)
    op.alter_column('sale_items', 'is_global_product',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_items', 'is_global_product',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_accounts_receivable_school_id'), table_name='accounts_receivable')
    op.drop_index(op.f('ix_accounts_receivable_client_id'), table_name='accounts_receivable')
    op.drop_table('accounts_receivable')
    op.drop_index(op.f('ix_balance_entries_school_id'), table_name='balance_entries')
    op.drop_index(op.f('ix_balance_entries_entry_date'), table_name='balance_entries')
    op.drop_index(op.f('ix_balance_entries_account_id'), table_name='balance_entries')
    op.drop_table('balance_entries')
    op.drop_index(op.f('ix_balance_accounts_school_id'), table_name='balance_accounts')
    op.drop_index(op.f('ix_balance_accounts_account_type'), table_name='balance_accounts')
    op.drop_table('balance_accounts')
    op.drop_index(op.f('ix_accounts_payable_school_id'), table_name='accounts_payable')
    op.drop_table('accounts_payable')
    # ### end Alembic commands ###
