"""Add global products tables

Revision ID: 768a2ea828c2
Revises: a85eb89bfb41
Create Date: 2025-12-08 23:57:04.022226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768a2ea828c2'
down_revision = 'a85eb89bfb41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_garment_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('global_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('garment_type_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('cost >= 0', name='chk_global_product_cost_positive'),
    sa.CheckConstraint('price >= 0', name='chk_global_product_price_positive'),
    sa.ForeignKeyConstraint(['garment_type_id'], ['global_garment_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_global_product_code')
    )
    op.create_index(op.f('ix_global_products_garment_type_id'), 'global_products', ['garment_type_id'], unique=False)
    op.create_table('global_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('min_stock_alert', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='chk_global_inventory_quantity_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['global_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', name='uq_global_product_inventory')
    )
    op.create_index(op.f('ix_global_inventory_product_id'), 'global_inventory', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_inventory_product_id'), table_name='global_inventory')
    op.drop_table('global_inventory')
    op.drop_index(op.f('ix_global_products_garment_type_id'), table_name='global_products')
    op.drop_table('global_products')
    op.drop_table('global_garment_types')
    # ### end Alembic commands ###
