"""Add global_product support to sale_items

Revision ID: afefdd76db63
Revises: 768a2ea828c2
Create Date: 2025-12-09 00:53:41.145578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afefdd76db63'
down_revision = '768a2ea828c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('global_product_id', sa.UUID(), nullable=True))
    # Add is_global_product with server_default for existing rows
    op.add_column('sale_items', sa.Column('is_global_product', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('sale_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_sale_items_global_product_id'), 'sale_items', ['global_product_id'], unique=False)
    op.create_foreign_key('fk_sale_items_global_product', 'sale_items', 'global_products', ['global_product_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sale_items_global_product', 'sale_items', type_='foreignkey')
    op.drop_index(op.f('ix_sale_items_global_product_id'), table_name='sale_items')
    op.alter_column('sale_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('sale_items', 'is_global_product')
    op.drop_column('sale_items', 'global_product_id')
    # ### end Alembic commands ###
