"""Add subtotal tax to orders and expand order_items

Revision ID: f12cb1e6c452
Revises: d868decca943
Create Date: 2025-12-07 21:08:34.565078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f12cb1e6c452'
down_revision = 'd868decca943'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # First add columns as nullable
    op.add_column('order_items', sa.Column('school_id', sa.UUID(), nullable=True))
    op.add_column('order_items', sa.Column('garment_type_id', sa.UUID(), nullable=True))
    op.add_column('order_items', sa.Column('size', sa.String(length=10), nullable=True))
    op.add_column('order_items', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('order_items', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('order_items', sa.Column('custom_measurements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('order_items', sa.Column('embroidery_text', sa.String(length=100), nullable=True))
    op.add_column('order_items', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('order_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_order_items_garment_type_id'), 'order_items', ['garment_type_id'], unique=False)
    op.create_index(op.f('ix_order_items_school_id'), 'order_items', ['school_id'], unique=False)
    op.drop_constraint('order_items_product_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'order_items', 'garment_types', ['garment_type_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'order_items', 'schools', ['school_id'], ['id'], ondelete='CASCADE')
    # Add orders columns as nullable first, then populate
    op.add_column('orders', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('orders', sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True))

    # Set default values for existing orders (subtotal = total, tax = 0)
    op.execute("UPDATE orders SET subtotal = total, tax = 0 WHERE subtotal IS NULL")

    # Now make them NOT NULL
    op.alter_column('orders', 'subtotal', nullable=False)
    op.alter_column('orders', 'tax', nullable=False)
    op.alter_column('sale_changes', 'change_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sale_changes', 'new_quantity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sale_changes', 'price_adjustment',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sale_changes', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='change_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sale_changes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sale_changes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_sale_changes_change_date', table_name='sale_changes')
    op.drop_index('ix_sale_changes_status', table_name='sale_changes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_sale_changes_status', 'sale_changes', ['status'], unique=False)
    op.create_index('ix_sale_changes_change_date', 'sale_changes', ['change_date'], unique=False)
    op.alter_column('sale_changes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('sale_changes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('sale_changes', 'status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='change_status_enum'),
               server_default=sa.text("'pending'::change_status_enum"),
               existing_nullable=False)
    op.alter_column('sale_changes', 'price_adjustment',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('sale_changes', 'new_quantity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sale_changes', 'change_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_column('orders', 'tax')
    op.drop_column('orders', 'subtotal')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_product_id_fkey', 'order_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_order_items_school_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_garment_type_id'), table_name='order_items')
    op.alter_column('order_items', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('order_items', 'notes')
    op.drop_column('order_items', 'embroidery_text')
    op.drop_column('order_items', 'custom_measurements')
    op.drop_column('order_items', 'gender')
    op.drop_column('order_items', 'color')
    op.drop_column('order_items', 'size')
    op.drop_column('order_items', 'garment_type_id')
    op.drop_column('order_items', 'school_id')
    # ### end Alembic commands ###
