"""
Pydantic Schemas Package
"""

# Base schemas
from app.schemas.base import (
    BaseSchema,
    IDModelSchema,
    TimestampSchema,
    SchoolIsolatedSchema,
)

# User and Authentication schemas
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserInDB,
    UserResponse,
    UserSchoolRoleBase,
    UserSchoolRoleCreate,
    UserSchoolRoleUpdate,
    UserSchoolRoleInDB,
    UserSchoolRoleResponse,
    Token,
    TokenData,
    LoginRequest,
    LoginResponse,
    PasswordChange,
    PasswordReset,
    PasswordResetConfirm,
)

# School schemas
from app.schemas.school import (
    SchoolBase,
    SchoolSettings,
    SchoolCreate,
    SchoolUpdate,
    SchoolInDB,
    SchoolResponse,
    SchoolListResponse,
    SchoolSummary,
)

# Product and Inventory schemas
from app.schemas.product import (
    GarmentTypeBase,
    GarmentTypeCreate,
    GarmentTypeUpdate,
    GarmentTypeInDB,
    GarmentTypeResponse,
    ProductBase,
    ProductCreate,
    ProductUpdate,
    ProductInDB,
    ProductResponse,
    ProductWithInventory,
    ProductListResponse,
    InventoryBase,
    InventoryCreate,
    InventoryUpdate,
    InventoryAdjust,
    InventoryInDB,
    InventoryResponse,
    LowStockProduct,
    InventoryReport,
)

# Client schemas
from app.schemas.client import (
    ClientBase,
    ClientCreate,
    ClientUpdate,
    ClientInDB,
    ClientResponse,
    ClientListResponse,
    ClientSummary,
)

# Sale schemas
from app.schemas.sale import (
    SaleItemBase,
    SaleItemCreate,
    SaleItemInDB,
    SaleItemResponse,
    SaleItemWithProduct,
    SaleBase,
    SaleCreate,
    SaleUpdate,
    SaleInDB,
    SaleResponse,
    SaleWithItems,
    SaleListResponse,
    SalesReport,
    TopProduct,
    SalesByPeriod,
    DailySalesSummary,
)

# Order schemas
from app.schemas.order import (
    OrderItemBase,
    OrderItemCreate,
    OrderItemUpdate,
    OrderItemInDB,
    OrderItemResponse,
    OrderItemWithGarment,
    OrderBase,
    OrderCreate,
    OrderUpdate,
    OrderPayment,
    OrderInDB,
    OrderResponse,
    OrderWithItems,
    OrderListResponse,
    OrdersReport,
    PendingOrder,
    OrdersByClient,
    ProductionSchedule,
)

# Accounting schemas
from app.schemas.accounting import (
    TransactionBase,
    TransactionCreate,
    TransactionUpdate,
    TransactionInDB,
    TransactionResponse,
    TransactionWithDetails,
    TransactionListResponse,
    ExpenseBase,
    ExpenseCreate,
    ExpenseUpdate,
    ExpensePayment,
    ExpenseInDB,
    ExpenseResponse,
    ExpenseWithTransaction,
    ExpenseListResponse,
    DailyCashRegisterBase,
    DailyCashRegisterCreate,
    DailyCashRegisterClose,
    DailyCashRegisterInDB,
    DailyCashRegisterResponse,
    DailyCashRegisterWithDetails,
    CashFlowSummary,
    DailyFinancialSummary,
    MonthlyFinancialReport,
    ExpensesByCategory,
    IncomeBySource,
    AccountingDashboard,
)

__all__ = [
    # Base
    "BaseSchema",
    "IDModelSchema",
    "TimestampSchema",
    "SchoolIsolatedSchema",
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserInDB",
    "UserResponse",
    "UserSchoolRoleBase",
    "UserSchoolRoleCreate",
    "UserSchoolRoleUpdate",
    "UserSchoolRoleInDB",
    "UserSchoolRoleResponse",
    "Token",
    "TokenData",
    "LoginRequest",
    "LoginResponse",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetConfirm",
    # School
    "SchoolBase",
    "SchoolSettings",
    "SchoolCreate",
    "SchoolUpdate",
    "SchoolInDB",
    "SchoolResponse",
    "SchoolListResponse",
    "SchoolSummary",
    # Product
    "GarmentTypeBase",
    "GarmentTypeCreate",
    "GarmentTypeUpdate",
    "GarmentTypeInDB",
    "GarmentTypeResponse",
    "ProductBase",
    "ProductCreate",
    "ProductUpdate",
    "ProductInDB",
    "ProductResponse",
    "ProductWithInventory",
    "ProductListResponse",
    "InventoryBase",
    "InventoryCreate",
    "InventoryUpdate",
    "InventoryAdjust",
    "InventoryInDB",
    "InventoryResponse",
    "LowStockProduct",
    "InventoryReport",
    # Client
    "ClientBase",
    "ClientCreate",
    "ClientUpdate",
    "ClientInDB",
    "ClientResponse",
    "ClientListResponse",
    "ClientSummary",
    # Sale
    "SaleItemBase",
    "SaleItemCreate",
    "SaleItemInDB",
    "SaleItemResponse",
    "SaleItemWithProduct",
    "SaleBase",
    "SaleCreate",
    "SaleUpdate",
    "SaleInDB",
    "SaleResponse",
    "SaleWithItems",
    "SaleListResponse",
    "SalesReport",
    "TopProduct",
    "SalesByPeriod",
    "DailySalesSummary",
    # Order
    "OrderItemBase",
    "OrderItemCreate",
    "OrderItemUpdate",
    "OrderItemInDB",
    "OrderItemResponse",
    "OrderItemWithGarment",
    "OrderBase",
    "OrderCreate",
    "OrderUpdate",
    "OrderPayment",
    "OrderInDB",
    "OrderResponse",
    "OrderWithItems",
    "OrderListResponse",
    "OrdersReport",
    "PendingOrder",
    "OrdersByClient",
    "ProductionSchedule",
    # Accounting
    "TransactionBase",
    "TransactionCreate",
    "TransactionUpdate",
    "TransactionInDB",
    "TransactionResponse",
    "TransactionWithDetails",
    "TransactionListResponse",
    "ExpenseBase",
    "ExpenseCreate",
    "ExpenseUpdate",
    "ExpensePayment",
    "ExpenseInDB",
    "ExpenseResponse",
    "ExpenseWithTransaction",
    "ExpenseListResponse",
    "DailyCashRegisterBase",
    "DailyCashRegisterCreate",
    "DailyCashRegisterClose",
    "DailyCashRegisterInDB",
    "DailyCashRegisterResponse",
    "DailyCashRegisterWithDetails",
    "CashFlowSummary",
    "DailyFinancialSummary",
    "MonthlyFinancialReport",
    "ExpensesByCategory",
    "IncomeBySource",
    "AccountingDashboard",
]
